version: '3'
services:
  neo4j:
    build: neo4j
    container_name: "neo4j"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # agree to use for development purposes only (production requires commercial license)
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"

      # user: neo4j, password: admin
      - "NEO4J_AUTH=neo4j/admin"

      # disable security procedures for installed plugins
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*"
      - "NEO4J_dbms_security_procedures_allowlist=apoc.*, gds.*"

  jupyter:
    build: jupyter
    container_name: "jupyter"
    volumes:
      - ./jupyter/notebooks:/notebooks
    working_dir: /notebooks
    ports:
      - "8888:8888"
    entrypoint: ["jupyter"]
    command: ["notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
